apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g0aey1vzi-python
  janus-idp.io/tekton: g0aey1vzi-python
  backstage.io/kubernetes-id: g0aey1vzi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g0aey1vzi-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
